# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true

# Minecraft Properties (version: compile; version_supported, version_filter: publish; lower, upper: excl. compat range)
minecraft_version = 1.20.1
minecraft_version_supported = [1.20.1]
minecraft_version_filter = releases
minecraft_version_lower = 1.19.4
minecraft_version_upper = 1.20.5

# File Name
minecraft_version_name = 1.20.1
archives_base_name=HungryCows

# Mod Properties
mod_version=2.2.2
mod_name=Hungry Cows
mod_name_short=Hungry Cows
maven_group=de.pnku

# Dependencies
jade_version=drol2x1P
owo_version=0.11.2+1.20
modmenu_version=7.2.2
emf_version=ryrcH1Vb
etf_version=cwZUQhK3
fnf_version=6hhOJ747
vbp_version=h4NWGgbG
platform_version=kPtnViap