# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true

# Minecraft Properties (version: compile; version_supported, version_filter: publish; lower, upper: excl. compat range)
minecraft_version = 1.21.5
minecraft_version_supported = [1.21.5]
minecraft_version_filter = releases
minecraft_version_lower = 1.21.4
minecraft_version_upper = 1.21.6

# File Name
minecraft_version_name = 1.21.5
archives_base_name=hungrycows

# Mod Properties
mod_version=2.2.0
mod_name=Hungry Cows
mod_name_short=Hungry Cows
maven_group=de.pnku

# Dependencies
jade_version=VNSIKHbV
owo_version=0.12.21+1.21.5
modmenu_version=14.0.1
emf_version=dwclLPuQ
etf_version=xtATusui
fnf_version=r2Vr8CUJ
yacl_version=oReM1Qvh
rlib_version=LeyfVUw5