name: publish

on:
  push:

jobs:
  build:
    uses: pnk2u/.github/.github/workflows/publish.yml@main
    secrets:
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}